config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search_book" => "books#search_book"
  
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
   resources :book_comments, only: [:create,:destroy]
   resource :favorites, only: [:create, :destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' =>'relationships#followings', as:'followings'
      get 'followers' =>'relationships#followers', as:'followers'
      get 'search_created' => 'users#search'
  end
  
  get 'search' => 'searches#search'
  resources :chats, only: [:show, :create]
  resources :groups, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
   get "join" => "groups#join"
   get "new/mail" => "groups#new_mail"
   get "send/mail" => "groups#send_mail"
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship",foreign_key: "follower_id",dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship",foreign_key: "followed_id",dependent: :destroy
  
  has_many :followings, through: :relationships,source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :favorited_books, through: :favorites, source: :book
  
  has_many :chats
  has_many :rooms, through: :user_rooms
  has_many :user_rooms
  
  has_many :read_counts,dependent: :destroy
  
  has_many :group_users,dependent: :destroy
  
  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def follow(user_id)
  relationships.create(followed_id:user_id)
  end
  
  def unfollow(user_id)
  relationships.find_by(followed_id:user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def self.looks(search,word)
    if search == "perfect_match"
    @user = User.where("name LIKE?","#{word}")
    elsif search == "forward_match"
       @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    #投稿数
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end
  
  def search
  @user = User.find(params[:user_id])
  @books = @user.books
  @book = Book.new
   if params[:created_at] == ""
   @search_book = "日付を選択してください"
   else
   create_at = params[:created_at]
   @search_book = @books.where(['created_at LIKE?',"#{create_at}%"]).count
   end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_book_count.html.erb
  <h3>投稿数の前日比・先週比</h3>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>今日の投稿数</th>
          <th>前日の投稿</th>
          <th>前日比</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @today_book.count %></td>
          <td><%= @yesterday_book.count %></td>
          <% if @yesterday_book.count == 0 %>
          <td>前日の投稿はなし</td>
          <% else %>
          <td><% @the_day_before = @today.book.count / @yesterday_book.count %>
              <%= (@the_day_before * 100).round %>%</td>
          <% end %>
        </tr>
        
        <tr>
          <td>今週の投稿数</td>
          <td>先週の投稿数</td>
          <td>先週比</td>
        </tr>
        <tr>
          <td><%= @this_week_book.count %></td>
          <td><%= @last_week_book.count %></td>
          <% if @last_week_book.count == 0 %>
          <td>先週の投稿はなし</td>
          <% else %>
          <td><% @the_week_before = @this_week_book / @last_week_book %>
              <%= @the_week_before * 100 %>%</td>
          <% end %>
        </tr>
      </tbody>
    </table>

app/views/users/_counts_graph.html.erb
<h2>7日間の投稿</h2>
      <table class="table table-bordered">
        <tr>
          <th>6日前</th>
          <th>5日前</th>
          <th>4日前</th>
          <th>3日前</th>
          <th>2日前</th>
          <th>1日前</th>
          <th>今日</th>
        </tr>
        <tr>
          <td><%= @books.created_6days_ago.count %></td>
          <td><%= @books.created_5days_ago.count %></td>
          <td><%= @books.created_4days_ago.count %></td>
          <td><%= @books.created_3days_ago.count %></td>
          <td><%= @books.created_2days_ago.count %></td>
          <td><%= @books.created_yesterday.count %></td>
          <td><%= @books.created_today.count %></td>
        </tr>
      </table>
      
      <canvas id="myLineChart"></canvas>
  <script>
    $(document).on('turbolinks:load', function() {
      var ctx = document.getElementById("myLineChart");
      var myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
          datasets: [
            {
              label: '投稿した本の数',
              data: [
                <%= @books.created_6days_ago.count %>,
                <%= @books.created_5days_ago.count %>,
                <%= @books.created_4days_ago.count %>,
                <%= @books.created_3days_ago.count %>,
                <%= @books.created_2days_ago.count %>,
                <%= @books.created_yesterday.count %>,
                <%= @books.created_today.count %>
              ],
              borderColor: "rgba(0,0,255,1)",
              backgroundColor: "rgba(0,0,0,0)",
              tension: 0.4
            }
          ],
        },
        options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          responsive: true,
          scales: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            x:{
              stacked: true
            },
          },
        }
      });
    });
  </script>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
     
      <% if user == current_user %>
        <td></td>
        <td><%= link_to 'Show',user %></td>
      <% else %>
       <% if current_user.following?(user) %>
        <td><%= link_to "フォロー外す" ,user_relationships_path(user.id),method: :delete %></td>
       <% else %>
        <td><%= link_to "フォローする",user_relationships_path(user.id),method: :post %></td>
       <% end %>
       <td><%= link_to 'Show',user %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
     <%= link_to user_followings_path(user.id) do %>
      <%= user.followings.count %></th>
     <% end %>
  </tr>
  <tr>
    <th>followers</th>
    <th>
     <%= link_to user_followers_path(user.id) do %>
     <%= user.followers.count %>
    </th>
   <% end %>
  </tr>
</table>


<div class='row'>
 <% if user == current_user %>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
 <% else %>
       <% if current_user.following?(user) %>
        <%= link_to "フォロー外す" ,user_relationships_path(user.id),method: :delete, class:"btn btn-primary" %>
         <% if current_user != user && current_user.following?(user)&&user.following?(current_user) %>
         <%=link_to "chatを始める",chat_path(user.id) %>
         <% end %>
       <% else %>
        <%= link_to "フォローする",user_relationships_path(user.id),method: :post, class:"btn btn-success" %>
       <% end %>
 <% end %>
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class="table table-bordered">
    <thead>
        <tr>
         <th>投稿数</th>
        </tr>
    </thead>
    
    <tbody>
        <tr>
            <td><%= search_book %></td>
        </tr>
    </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followings.html.erb
followings

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">

<h2>User info</h2>
<%= render 'info', user: current_user %>

<h2 class="mt-3">New book</h2>
<%= render 'books/form', book: @book %>
  </div>
  
 <div class="col-md-8 offset-md-1">
<h2>Users</h2>
<%= link_to "グループを作成する",new_group_path %>|
<%= link_to "グループ一覧",groups_path %>
<%= render 'index',users: @users %>
 </div>
  
 </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render "search",search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      
      <%= form_with url: user_search_created_path(@user), method: :get, local: false do |f| %>
      <%= f.date_field :created_at %>
      <%= f.submit "検索" %>
      <% end %>
      
      <div id="search_result">
        <% if @search_book.present? %>
        <%= render "search",search_book: @search_book %>
        <% end %>
      </div>
      
    
    
      
    </div>
  </div>
</div>