config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search_book" => "books#search_book"
  
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
   resources :book_comments, only: [:create,:destroy]
   resource :favorites, only: [:create, :destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' =>'relationships#followings', as:'followings'
      get 'followers' =>'relationships#followers', as:'followers'
      get 'search_created' => 'users#search'
  end
  
  get 'search' => 'searches#search'
  resources :chats, only: [:show, :create]
  resources :groups, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
   get "join" => "groups#join"
   get "new/mail" => "groups#new_mail"
   get "send/mail" => "groups#send_mail"
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
  has_many :read_counts,dependent: :destroy
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
  scope :latest, -> {order(creater_at: :desc)}
  scope :star_count, -> {order(star: :desc)}
  
  scope :created_today, -> { where(created_at: Time.zone.now.all_day)}
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day)}
  scope :created_2days_ago, -> { where(created_at: 2.day.ago.all_day)}
  scope :created_3days_ago, -> { where(created_at: 3.day.ago.all_day)}
  scope :created_4days_ago, -> { where(created_at: 4.day.ago.all_day)}
  scope :created_5days_ago, -> { where(created_at: 5.day.ago.all_day)}
  scope :created_6days_ago, -> { where(created_at: 6.day.ago.all_day)}
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day)}
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day)}
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.looks(search,word)
    if search == "perfect_match"
       @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
       @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
  def self.search(search_word)
    Book.where(['category LIKE?',"#{search_word}"])
  end
  
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
    #閲覧数のための表記
     #unless ReadCount.find_by(user_id: current_user.id, book_id: @book.id) #1人一回の場合
     current_user.read_counts.create(book_id: @book.id)
  end

  def index
    @books = Book.includes(:favorited_users).sort{|a,b| b.favorited_users.size <=> a.favorited_users.size}
    @book = Book.new
    
    if params[:latest]
    @books = Book.latest
    elsif params[:star_count]
    @books = Book.star_count
    else
    @books = Book.all
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "successfully delete book!"
  end
  
  def search_book
  @book = Book.new
  @books = Book.search(params[:keyword])
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:star,:category)
  end
  
  def ensure_correct_user
   @book = Book.find(params[:id])
   unless @book.user == current_user
     redirect_to books_path
   end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>
  
  <% if book.id.nil? %>
   <div class="form-group",id="star" %>
     <%= f.label :star %>
     <%= f.hidden_field :star, id: :review_star, class:'form-control' %>
     <div id='post_raty'></div>
   </div>
   <script>
     $(document).on('turbolinks:load',function() {
       let elem = document.querySelector('#post_raty');
       if (elem == null) return;
       
       elem.innerHTML = ""
       let opt = {
         starOn: "<%= asset_path('star-on.png') %>",
         starOff: "<%= asset_path('star-off.png') %>",
         scoreName: 'book[star]',
       };
       raty(elem,opt);
     });
   </script>
   <% else %>
    <div class="form-group">
      <%= render "static_rate",book: book %>
    </div>
   <% end %>
     
  
  
  
  
  
  
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td><%= link_to book.category,search_book_path(keyword: book.category) %></td>
       
        <td id="favorite_btn_<%= book.id %>">
        <%= render 'favorites/favorites', book: book %>
        </td>
        
        <td>
          コメント数:<%= book.book_comments.count %>
        </td>
        <td>閲覧数:<%= book.read_counts.count %></td>
        <td><%= render "books/static_rate",book: book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_search_book.html.erb
<% if user_signed_in? %>
    <%= form_with url: search_book_path, method: :get do |f| %>
    <%= f.text_field :keyword %>
    <%= f.submit "タグ検索"  %>
    <% end %> 
<% end %>

app/views/books/_static_rate.html.erb
<div id="star_<%= book.id %>"></div>
<script>
$(document).on('turbolinks:load', function(){
 let elem = document.querySelector("#star_<%= book.id %>");
 if (elem == null) return;
 
 elem.innerHTML = "";
 let opt = {
     starOn: "<%= asset_path('star-on.png') %>",
     starOff: "<%= asset_path('star-off.png') %>",
     score: "<%= book.star %>",
     readOnly: true,
           };
     raty(elem,opt);
 });
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
 <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <p><%= link_to "新しい順",books_path(latest: "true") %>
         | <%= link_to "評価の高い順",books_path(star_count: "true") %></p>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to(book.user) do %>
                <%= image_tag book.user.get_profile_image, size:'50x50' %>
                <% end %>
              </td>
              <td><%= link_to book.title,book %></td>
              <td><%= book.body %></td>
             
              <td id="favorite_btn_<%= book.id %>">
              <%= render 'favorites/favorites', book: book %>
              </td>
              
              <td>
                コメント数<%= book.book_comments.count %>
              </td>
              <td>閲覧数:<%= book.read_counts.count %></td>
              <td><%= render "static_rate",book: book %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/search_book.html.erb
<table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>tag</th>
            <th colspan="3"></th>
          </tr>
         </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to(book.user) do %>
                <%= image_tag book.user.get_profile_image, size:'50x50' %>
                <% end %>
              </td>
              <td><%= link_to book.title,book %></td>
              <td><%= book.body %></td>
              <td><%= link_to book.category,search_book_path(keyword: book.category) %></td>
             
              <td id="favorite_btn_<%= book.id %>">
              <%= render 'favorites/favorites', book: book %>
              </td>
              
              <td>
                コメント数<%= book.book_comments.count %>
              </td>
              <td>閲覧数:<%= book.read_counts.count %></td>
              <td><%= render "static_rate",book: book %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><%= link_to @book.category, search_book_path(keyword: @book.category) %></td>
          
          <td id="favorite_btn_<%= @book.id %>">
           <%= render 'favorites/favorites', book: @book %>
          </td>
        
        <td class="book-comments-counter">
          <%= render "book_comments/counter",book: @book %>
        </td>
        <td>閲覧数:<%= @book.read_counts.count %></td>
        <td><%= render "books/static_rate",book: @book %></td>
        
         <% if user_signed_in? && current_user.id == @book.user_id %>
            <td><%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
         <% end %>
        </tr>
      </table>
      
    <div class="comment-index"><%= render "book_comments/book_comments", book: @book %></div>
    <div class="comment-area"><%= render "book_comments/book_comments_area",book: @book, book_comment: @book_comment %></div>
      
      
     
      
    
    </div>
  </div>
</div>